export const Projects_arr = [
  {
    name: "TalkToo",
    description: `Enhanced performance by 80% using optimization techniques in React Native and React Native Web. Built reusable UI components and integrated generative AI tools (OpenAI, Gemini, Claude) to power intelligent assistants. Developed backend APIs with Node.js and SQL`,
    oneLineDescription:
      "Create custom AI companions for productivity, learning, and creativity.",
    madeAt: "Agile Soft Systems",
    tech: [
      "React Native",
      "ReactJS",
      "NodeJS",
      "SQL",
      "Generative AI",
    ],
    role: ["Sr. Developer and Mentor"],
    year: "2024",
    showAsDisplay: true,
  },
  {
    name: "SoundGen AI",
    description: `Redesigned UI using Tailwind CSS and improved load time from 5 seconds to under 300 ms. Implemented frontend optimization techniques such as code-splitting, dynamic imports, and memoization, cutting initial load time by 40%.`,
    oneLineDescription: "Generate music with AI.",
    madeAt: "Agile Soft Systems",
    tech: ["ReactJS", "NodeJS", "SQL", "Generative AI"],
    role: ["Performance Optimizer"],
    year: "2024",
    showAsDisplay: true,
  },
  {
    name: "Moshi AI",
    description: `Built a virtual assistant capable of researching, summarizing, and generating digital content like images, videos, and documents. Developed clean, responsive UI with HTML, CSS, and JavaScript, ensuring fully autonomous task execution and seamless interaction workflows`,
    oneLineDescription: "Generate content with AI.",
    madeAt: "Agile Soft Systems",
    tech: ["NextJS", "NodeJS", "SQL", "Generative AI"],
    role: ["Sr. Developer"],
    year: "2025",
    showAsDisplay: true,
  },
  {
    name: "3Efreet",
    description: `3Efreet is your hassle-free delivery solution. Choose flexible prices, select smart package sizes, and connect with qualified delivery partners. Book in seconds, track easily, and rate your experience—all with 3Efreet!`,
    tech: ["React Native", "ReactJS", "NodeJS", "MongoDB"],
    oneLineDescription:
      "Effortlessly book and track deliveries with smart pricing and features.",
    role: [
      "Project Manager",
      "Sr. React Native Developer",
      "Solution Architect",
    ],
    year: "2021",
    madeAt: "Independent Consultant",
    showAsDisplay: false,
  },
  {
    name: "Skill india digital",
    description: `Created multilingual React Native interfaces for onboarding, registration, and profile flows. Integrated eKYC using Aadhaar APIs and helped implement AI-powered course recommendation features using Node.js, Python, and SQL backends`,
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    oneLineDescription:
      "A national platform for skilling, upskilling, and reskilling in India.",
    role: ["Sr. React Native Developer"],
    madeAt: "Shine Infosoft",
    year: "2023",
    showAsDisplay: true,
  },
  {
    name: "Discreet Lobby",
    description: `Discreet Lobby enables users to connect with others privately and gain access to exclusive events like pool and house parties organized by admins. Enjoy a secure, discreet way to socialize and attend select gatherings.`,
    oneLineDescription:
      "Connect privately and attend exclusive events securely.",
    tech: ["React Native", "ReactJS", "NodeJS", "MongoDB"],
    role: ["Sr. React Native Developer"],
    year: "2020",
    madeAt: "Independent Consultant",
    showAsDisplay: true,
  },
  {
    name: "InstaCharge",
    description: `InstaCharge is the simplest EV charging app. Just register with your phone number and start charging. Access India’s largest EV charger network, pay easily, and navigate effortlessly in multiple Indian languages.`,
    oneLineDescription:
      "India’s easiest EV charging solution with multilingual support.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    year: "2021",
    madeAt: "Independent Consultant",
    showAsDisplay: false,
  },
  {
    year: "2020",
    name: "Beauty Soft",
    oneLineDescription:
      "Streamline salon operations with an all-in-one management tool.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2020",
    name: "ChillBaby",
    oneLineDescription:
      "Monitor your baby with IoT-enabled smart seat technology.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "At a Tech Firm",
  },
  {
    year: "2020",
    name: "Shaamel",
    oneLineDescription:
      "Bridge users with service providers for convenient at-home services.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "At a Tech Firm",
  },
  {
    year: "2020",
    name: "iCard",
    oneLineDescription:
      "Manage student data efficiently with a simple app solution.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2020",
    name: "NovaDating",
    oneLineDescription:
      "A unique dating app with an innovative user experience.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2020",
    name: "Powertrac",
    oneLineDescription:
      "Manage inventory and enable speedy food takeaway for cafes.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2021",
    name: "SurfWallet",
    oneLineDescription: "A secure blockchain-based wallet application.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2021",
    name: "TNC-CRM",
    oneLineDescription: "A CRM app to manage salons and their workforce.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["React Native Developer"],
    madeAt: "Independent Consultant",
  },
  {
    year: "2022",
    name: "Cookpals",
    oneLineDescription:
      "Connect through recipes with this unique dating platform.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Excellent Web World",
  },
  {
    year: "2022",
    name: "Canteeny",
    oneLineDescription:
      "Simplify franchise management for multi-canteen operations.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Excellent Web World",
  },
  {
    year: "2022",
    name: "HelpLah",
    oneLineDescription: "Book reliable home services quickly and easily.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Excellent Web World",
  },
  {
    year: "2022",
    name: "Saloon App",
    oneLineDescription: "Manage salons, staff, and operations seamlessly.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Excellent Web World",
  },
  {
    year: "2023",
    name: "Aladdin",
    oneLineDescription: "An app for booking reliable home-based services.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Shine Infosoft",
  },
  {
    year: "2024",
    name: "First 30 Day",
    oneLineDescription:
      "An app for churches to share 30-day lessons and tasks with users.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Shine Infosoft",
  },
  {
    year: "2024",
    name: "Influencer (Delphi AI)",
    oneLineDescription:
      "AI-powered platform to connect influencers with their followers.",
    tech: ["React Native", "ReactJS", "NodeJS", "SQL"],
    role: ["Sr. React Native Developer"],
    madeAt: "Shine Infosoft",
  },
];
