// ============================================================
// All portfolio content data
// ============================================================

export const META = {
  name: "Hitanshu Gajjar",
  nameShort: "HG",
  logo: "HG / HITANSHU GAJJAR",
  title: "Sr. Software Engineer",
  location: "INDIA · GLOBALLY",
  email: "hitanshu.hexxum@gmail.com",
  tagline:
    "Crafting high-performance web & mobile experiences with a global mindset and 8+ years of real-world engineering.",
  availability: "OPEN TO OPPORTUNITIES",
  portfolio: "PORTFOLIO · 2016 – 2026",
  edition: "VOL. 01 · EDITION 02",
};

export const ROLES = [
  "React Native Engineer",
  "Sr. Software Engineer",
  "Team Lead",
  "AI Integration Specialist",
];

export const ABOUT = {
  label: "01 · ABOUT",
  headline: ["Engineering,", "not", "just coding."],
  body: [
    "I'm Hitanshu Gajjar — a Frontend-focused engineer with 8+ years of building robust, scalable web and mobile apps. The journey began in late 2016 as an Android developer; from mid-2019 I specialised in React & React Native, shipping high-performance, cross-platform products for clients across three continents.",
    "I'm fluent in React.js, Next.js, and React Native — comfortable across the full frontend spectrum. I've also led teams and managed projects for three+ years, blending engineering depth with strategic planning.",
    "Currently I'm working as a Sr. Software Engineer at Fulcrum Digital — delivering enterprise-grade applications, architecting frontend systems from scratch, and integrating Generative AI (OpenAI, Gemini, Claude) into production workflows.",
  ],
};

export const STATS = [
  { value: 9, suffix: "+", label: "Years experience" },
  { value: 22, suffix: "+", label: "Apps shipped" },
  { value: 3, suffix: "", label: "Continents" },
  { value: 4, suffix: "", label: "Companies" },
];

export const SKILLS = {
  label: "02 · TOOLKIT",
  headline: "The stack I reach for.",
  sub: "25+ TECHNOLOGIES · SHIPPING DAILY",
  tags: [
    "React Native",
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "Node.js",
    "Redux · Saga · Thunk",
    "React Query",
    "Context API",
    "Tailwind CSS",
    "NativeBase",
    "Generative AI",
    "OpenAI",
    "Gemini",
    "Claude",
    "Firebase",
    "GraphQL",
    "Swift",
    "Kotlin · Java",
    "MongoDB · SQL",
    "Jest · RTL",
    "Git",
    "Python",
    "ESLint",
  ],
};

export const MARQUEE_ITEMS = [
  "Performance Optimisation",
  "AI Integration",
  "8+ Years Shipping",
  "React Native Expert",
  "Mobile-First",
  "Cross-Platform",
  "Clean Architecture",
  "Team Leadership",
];
export const FEATURED = [
  {
    id: 1,
    title: "India's First Life Insurance",
    company: "Fulcrum Digital",
    year: "2026",
    role: "Sr. Software Engineer",
    tags: ["React.js", "TypeScript", "Enterprise", "VAPT"],
    description:
      "India's first fully digital life insurance platform — architected the entire frontend from scratch, delivering with zero VAPT security vulnerabilities across a complex, regulated domain.",
  },
  {
    id: 2,
    title: "AQS Tokio Marine",
    company: "Fulcrum Digital",
    year: "2026",
    role: "Sr. Software Engineer",
    tags: ["React.js", "TypeScript", "Legacy Migration", "ASP.NET"],
    description:
      "Complete rewrite of a 26-year-old ASP.NET/VBScript insurance system to modern React — architected purely from legacy code analysis, driving performance, global scalability, and maintainability.",
  },
  {
    id: 3,
    title: "Moshi AI",
    company: "Agile Soft Systems",
    year: "2025",
    role: "Sr. Developer",
    tags: ["Next.js", "Node.js", "GenAI", "SQL"],
    description:
      "Built a virtual assistant capable of researching, summarizing, and generating digital content like images, videos, and documents. Clean, responsive UI with fully autonomous task execution.",
  },
  {
    id: 4,
    title: "TalkToo",
    company: "Agile Soft Systems",
    year: "2024",
    role: "Sr. Developer & Mentor",
    tags: ["React Native", "React.js", "Node.js", "GenAI"],
    description:
      "Custom AI companions for productivity, learning & creativity. Enhanced performance by 80% using React Native optimization techniques and integrated OpenAI, Gemini, and Claude.",
  },
  {
    id: 5,
    title: "Skill India Digital",
    company: "Shine Infosoft",
    year: "2023",
    role: "Sr. React Native Developer",
    tags: ["React Native", "Node.js", "SQL", "eKYC"],
    description:
      "National platform for skilling, upskilling, and reskilling in India. Multilingual interfaces, eKYC via Aadhaar APIs, and AI-powered course recommendations.",
  },
  {
    id: 6,
    title: "3Efreet",
    company: "Independent",
    year: "2021",
    role: "Project Manager · Architect",
    tags: ["React Native", "Node.js", "MongoDB"],
    description:
      "Hassle-free delivery booking & tracking. Choose flexible prices, select smart package sizes, connect with delivery partners — book in seconds, track in real time.",
  },
];

export const EXPERIENCE = [
  {
    id: 1,
    role: "Sr. Software Engineer",
    company: "Fulcrum Digital",
    period: "Sep 2025 – Present",
    location: "India · Remote",
    stack: ["React.js", "Next.js", "TypeScript", "Enterprise Architecture"],
    highlights: [
      "Architected India's first life insurance digital platform — delivered with zero VAPT security issues",
      "Leading rewrite of a 26-year-old ASP.NET/VBScript legacy system (AQS Tokio Marine) to modern React",
      "Designed scalable frontend architecture from legacy codebase analysis with no existing documentation",
      "Drove multiple refactoring initiatives for global performance and maintainability improvements",
    ],
  },
  {
    id: 2,
    role: "Sr. Software Engineer",
    company: "Agile Soft System Inc.",
    period: "Mar 2024 – Aug 2025",
    location: "India · Remote",
    stack: ["React Native", "JavaScript", "TypeScript", "React.js", "Node.js"],
    highlights: [
      "Led frontend and mobile development using React Native, React.js, and Next.js",
      "Improved system performance and usability by optimizing components and backend APIs in Node.js",
      "Mentored developers, conducted code reviews, and automated workflows using Google Apps Script and AppSheet",
    ],
  },
  {
    id: 3,
    role: "Team Lead · React Native",
    company: "Shine Infosoft",
    period: "Jul 2023 – Feb 2024",
    location: "India · Remote",
    stack: ["React Native", "JavaScript", "TypeScript", "React.js", "Node.js"],
    highlights: [
      "Revamped legacy code into modular React Native components, improving app performance and user experience",
      "Leveraged Redux-Saga and Context API for robust state management",
      "Collaborated on version control, resolved merge conflicts, and supported releases with QA coordination",
    ],
  },
  {
    id: 4,
    role: "Team Lead · React Native",
    company: "Excellent Web World",
    period: "Jul 2022 – Jul 2023",
    location: "India · Remote",
    stack: ["React Native", "JavaScript", "TypeScript"],
    highlights: [
      "Developed high-quality cross-platform features delivering design-consistent apps across iOS and Android",
      "Integrated Firebase for authentication and real-time functionality",
      "Maintained code quality with ESLint, Prettier, and clear documentation",
    ],
  },
];

export const PROJECTS_ARCHIVE = [
  {
    year: 2026,
    title: "India's First Life Insurance",
    company: "Fulcrum Digital",
    companyKey: "FULCRUM",
    tech: ["React"],
    stack: "React.js · TypeScript · Enterprise",
    description:
      "India's first fully digital life insurance platform — zero VAPT security issues.",
    featured: true,
  },
  {
    year: 2026,
    title: "AQS Tokio Marine",
    company: "Fulcrum Digital",
    companyKey: "FULCRUM",
    tech: ["React"],
    stack: "React.js · TypeScript · Legacy Migration",
    description:
      "Rewrite of a 26-year-old ASP.NET/VBScript insurance system to modern React.",
    featured: true,
  },
  {
    year: 2025,
    title: "Moshi AI",
    company: "Agile Soft Systems",
    companyKey: "AGILE",
    tech: ["GenAI"],
    stack: "Next.js · Node.js · SQL · GenAI",
    description: "Generate content with AI.",
    featured: true,
  },
  {
    year: 2024,
    title: "TalkToo",
    company: "Agile Soft Systems",
    companyKey: "AGILE",
    tech: ["RN", "GenAI"],
    stack: "React Native · React.js · Node.js · SQL · GenAI",
    description:
      "Create custom AI companions for productivity, learning, and creativity.",
    featured: true,
  },
  {
    year: 2024,
    title: "SoundGen AI",
    company: "Agile Soft Systems",
    companyKey: "AGILE",
    tech: ["GenAI"],
    stack: "React.js · Node.js · SQL · GenAI",
    description: "Generate music with AI.",
    featured: false,
  },
  {
    year: 2024,
    title: "First 30 Day",
    company: "Agile Soft Systems",
    companyKey: "SHINE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description:
      "An app for churches to share 30-day lessons and tasks with users.",
    featured: false,
  },
  {
    year: 2024,
    title: "Influencer (Delphi AI)",
    company: "Agile Soft Systems",
    companyKey: "SHINE",
    tech: ["RN", "GenAI"],
    stack: "React Native · Node.js · SQL",
    description:
      "AI-powered platform to connect influencers with their followers.",
    featured: false,
  },
  {
    year: 2023,
    title: "Skill India Digital",
    company: "Shine Infosoft",
    companyKey: "SHINE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description:
      "A national platform for skilling, upskilling, and reskilling in India.",
    featured: true,
  },
  {
    year: 2023,
    title: "Aladdin",
    company: "Shine Infosoft",
    companyKey: "SHINE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "An app for booking reliable home-based services.",
    featured: false,
  },
  {
    year: 2022,
    title: "Cookpals",
    company: "Excellent Web World",
    companyKey: "EWW",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Connect through recipes with this unique dating platform.",
    featured: false,
  },
  {
    year: 2022,
    title: "Canteeny",
    company: "Excellent Web World",
    companyKey: "EWW",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Simplify franchise management for multi-canteen operations.",
    featured: false,
  },
  {
    year: 2022,
    title: "HelpLah",
    company: "Excellent Web World",
    companyKey: "EWW",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Book reliable home services quickly and easily.",
    featured: false,
  },
  {
    year: 2022,
    title: "Saloon App",
    company: "Excellent Web World",
    companyKey: "EWW",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Manage salons, staff, and operations seamlessly.",
    featured: false,
  },
  {
    year: 2021,
    title: "3Efreet",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN", "MONGO"],
    stack: "React Native · React.js · Node.js · MongoDB",
    description:
      "Effortlessly book and track deliveries with smart pricing and features.",
    featured: true,
  },
  {
    year: 2021,
    title: "InstaCharge",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description:
      "India's easiest EV charging solution with multilingual support.",
    featured: false,
  },
  {
    year: 2021,
    title: "SurfWallet",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "A secure blockchain-based wallet application.",
    featured: false,
  },
  {
    year: 2021,
    title: "TNC-CRM",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "A CRM app to manage salons and their workforce.",
    featured: false,
  },
  {
    year: 2020,
    title: "Discreet Lobby",
    company: "At a Tech Firm",
    companyKey: "INDIE",
    tech: ["RN", "MONGO"],
    stack: "React Native · Node.js · MongoDB",
    description: "Connect privately and attend exclusive events securely.",
    featured: false,
  },
  {
    year: 2020,
    title: "Beauty Soft",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description:
      "Streamline salon operations with an all-in-one management tool.",
    featured: false,
  },
  {
    year: 2020,
    title: "ChillBaby",
    company: "At a Tech Firm",
    companyKey: "TECH",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL · IoT",
    description: "Monitor your baby with IoT-enabled smart seat technology.",
    featured: false,
  },
  {
    year: 2020,
    title: "Shaamel",
    company: "At a Tech Firm",
    companyKey: "TECH",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description:
      "Bridge users with service providers for convenient at-home services.",
    featured: false,
  },
  {
    year: 2020,
    title: "iCard",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Manage student data efficiently with a simple app solution.",
    featured: false,
  },
  {
    year: 2020,
    title: "NovaDating",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "A unique dating app with an innovative user experience.",
    featured: false,
  },
  {
    year: 2020,
    title: "Powertrac",
    company: "Independent",
    companyKey: "INDIE",
    tech: ["RN"],
    stack: "React Native · Node.js · SQL",
    description: "Manage inventory and enable speedy food takeaway for cafes.",
    featured: false,
  },
];

export const LINKS = {
  linkedin: "https://linkedin.com/in/hitanshu-gajjar",
  github: "https://github.com/hitanshu-gajjar",
  email: "mailto:hitanshu.hexxum@gmail.com",
};
